### ISSUE TITLE
ftxvalidator installation errors with INSTALL.md instructions on macOS 10.12.6

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#1960]
## Observed behaviour

Unable to execute ftxvalidator using the installation instructions on the INSTALL.md page

## Expected behaviour

Expected to install ftxvalidator with GUI installation tool or via command line instructions and perform macOS font validations.

## Resources and exact process needed to replicate

macOS 10.12.6
ftxvalidator via Font_Tools_for_Xcode_9.dmg download from Apple developer site (download 7/5/18)

1) Attempted installation with the dmg GUI installer and received no errors during installation attempt.  Opened iTerm2 and tried to execute the command `ftxvalidator -h` and received the following error message:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN3ftx8FTStringC1EPKcz
  Referenced from: /usr/bin/ftxvalidator (which was built for Mac OS X 10.12)
  Expected in: /Library/Frameworks/FontToolbox.framework/Versions/A/FontToolbox

dyld: Symbol not found: __ZN3ftx8FTStringC1EPKcz
  Referenced from: /usr/bin/ftxvalidator (which was built for Mac OS X 10.12)
  Expected in: /Library/Frameworks/FontToolbox.framework/Versions/A/FontToolbox

[1]    4295 abort      ftxvalidator -h
```

2) Attempted install with command line instructions provided on your INSTALL.md documentation and received the following at the `hdiutil attach osxfonttools.dmg ;` step:

```
hdiutil: attach failed - No such file or directory
```

Thoughts?  Seems that there is a problem with the installed FontToolbox.framework.  I can verify that the FontToolbox framework is present on that path and was last modified 9/26/2011.

Related issue report: https://github.com/googlefonts/fontbakery/issues/1927

**Comment by davelab6** [comment]
Maybe needs a newer macOS?

**Comment by chrissimpkins** [comment]
Should have mentioned.  I have XCode 9.2 installed

**Comment by chrissimpkins** [comment]
> Maybe needs a newer macOS

Will give it a try on 10.13.  Will let you know.

**Comment by chrissimpkins** [comment]
Install works with 10.13.5 + XCode v9.4.1...

The FontTools.framework is installed with the execution of the .dmg installer downloaded from the Apple developer site.  On macOS 10.13.5 / XCode 9.4.1 I get an updated framework on the path `/Library/Frameworks/FontToolbox.framework/Versions/A/FontToolbox`:

```
6.5M Sep  2  2017 FontToolbox
```

I suppose ok to close?  Not sure that there is anything to do about it here.  FYI.

**Comment by chrissimpkins** [comment]
some of us are slower than others :)

**Comment by eliheuer** [comment]
@chrissimpkins I was on 10.11 on a 2008 Mac until this issue finally pushed me to upgrade. I suspect this will be a big pain point if `fontbakery` sees increased usage. 

ftxvalidator install worked fine for me on 10.13.6 as well.

**Comment by chrissimpkins** [comment]
Thanks Eli.  It seems that Apple updated the framework as of 10.13.  My version of the framework in 10.12 was last changed in 2011...

**Comment by HinTak** [comment]
BTW, you can check this sort of issue if you have otools (should be part of Xcode):

you do something like this:

```
otools -L /usr/bin/ftxvalidator
otoolls -L /Library/Frameworks/FontToolbox.framework/Versions/A/FontToolbox
```

(sorry not actually in front of a box with those... the syntax might be different).

This command prints the actual library versions expected/embedded within the binaries concerned.

If you are armed with an OS X cross-compiling tool chain such as osxcross on Linux or windows, you can do the same with `darwin-apple...-otools` also, where `...` is the tool chain version. I do that all the time with my cross-compiled FontVal OSX binaries to check and verify their dependencies.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/pull/1997 adds the documentation recommended by @davelab6 in https://github.com/googlefonts/fontbakery/issues/1960#issuecomment-403151180
