### ISSUE TITLE
com.google.fonts/check/metadata/can_render_samples - AttributeError: 'NoneType'

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3495]
## Observed behaviour

After upgrading Fontbakery to 0.8.3, there is an ERROR reported for this new check. 

<details>
<summary>💔 <b>ERROR:</b> Check samples can be rendered.</summary>

* [com.google.fonts/check/metadata/can_render_samples](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/can_render_samples)
<pre>--- Rationale ---
In order to prevent tofu from being seen on fonts.google.com, this check
verifies that all samples provided on METADATA.pb can be properly rendered by
the font.</pre>

* 💔 **ERROR** Failed with AttributeError: 'NoneType' object has no attribute 'sample_glyphs'

</details>

## Resources and exact process needed to replicate
[Licorice-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/7462414/Licorice-Regular.ttf.zip)

**Comment by RosaWagner** [comment]
We also have the same ERROR
I guess #3494 will fix it?

**Comment by felipesanches** [comment]
I've just reviewed and merged that PR. Can you verify whether this solves the problem?

**Comment by vv-monsalve** [comment]
After installing it with `pip install git+https://github.com/googlefonts/fontbakery` the ERROR is still reported.

**Comment by felipesanches** [comment]
ok, I'll double check that locally then.

**Comment by felipesanches** [comment]
![Screenshot from 2021-11-05 03-08-51](https://user-images.githubusercontent.com/213676/140466153-96dd571e-541f-4b0e-a355-5f20976518d5.png)

Naturally, as this is a check involving a `METADATA.pb` file, the single TTF file provided is not enough to reproduce the bug. In these cases, please also attach the metadata file to the issue.

I think this font project may be in some github repo, so I'll look for it now, to get a copy of the file needed.

**Comment by felipesanches** [comment]
OK, got the repo (https://github.com/googlefonts/licorice) but the METADATA.pb file is not there (I guess that's because it must be generated by the font packager)

**Comment by felipesanches** [comment]
I faked it by copying a METADATA.pb from from some other font project that has sample_glyphs surely not supported by Licorice, and the check gave me a good result:

![Screenshot from 2021-11-05 03-28-35](https://user-images.githubusercontent.com/213676/140468044-7d249a5d-b6a9-4bcd-936b-452b494761a5.png)


I did the same with a METADATA.pb that does not include `sample_glyphs` entries, and that also looks fine:

![Screenshot from 2021-11-05 03-29-09](https://user-images.githubusercontent.com/213676/140468135-f3a02320-3837-4bbf-8bcb-2817c4e80ffd.png)

**Comment by felipesanches** [comment]
Finally, I looked once more to the check implementation and I'm pretty sure that's correct. There's no way for one to get an ERROR message like that `AttributeError: 'NoneType' object has no attribute 'sample_glyphs'` unless it is not the latest version of FontBakery that is being run:

![Screenshot from 2021-11-05 03-40-45](https://user-images.githubusercontent.com/213676/140469145-2dc911cc-91b6-43c8-a25f-37d839ba2dda.png)

But that ERROR would definitely happen on FB v0.8.2 if the project being checked lacks a `METADATA.pb` file.

All of these things lead me to the conclusion that this is actually a side effect of issue #3456, so I will close this one. But feel free to reopen this issue in the future if needed.

**Comment by vv-monsalve** [comment]
> OK, got the repo (https://github.com/googlefonts/licorice) but the METADATA.pb file is not there (I guess that's because it must be generated by the font packager)

Well yes indeed, the METADATA.pb is not supposed to be part of either of the designer's (or development) repo, nor therefore in the local clones of them. It is only be included when the font is actually [added](https://github.com/googlefonts/gftools/blob/main/bin/gftools-add-font.py) to the [google/fonts repo](https://github.com/googlefonts/gf-docs/tree/main/Spec#the-googlefonts-repo). However, the Fontbakery tests are run both locally and on the development repositories, where the ERROR [keeps being reported](https://github.com/googlefonts/waterfall/runs/4111696211?check_suite_focus=true#step:9:492), not only for Literata and even under the latest `0.8.3` version (both locally and in the CI GHA).

> But that ERROR would definitely happen on FB v0.8.2 if the project being checked lacks a METADATA.pb file.

From the above (the METADATA.pb file not being intended to be part of the development repo or its local clone) the check will keep having an ERROR result on those scenarios.

> All of these things lead me to the conclusion that this is actually a side effect of issue #3456, so I will close this one. But feel free to reopen this issue in the future if needed.

The latest installations of FB are not reporting that issue anymore, and the `pip install --upgrade fontbakery` command was run to have the latest version before reporting this in any case (as noted in the original text of the issue). 
It seems more likely that if the check relies on a file that is only intended to be included in the google/fonts repo it is going to have the same result when run in a different location where there will be no METADATA.pb file.

----

Fontbakery version: 0.8.3

<details>
<summary><b>[14] TwinkleStar-Regular.ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Check samples can be rendered.</summary>

* [com.google.fonts/check/metadata/can_render_samples](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/can_render_samples)
<pre>--- Rationale ---
In order to prevent tofu from being seen on fonts.google.com, this check
verifies that all samples provided on METADATA.pb can be properly rendered by
the font.</pre>

* 💔 **ERROR** Failed with AttributeError: 'NoneType' object has no attribute 'sample_glyphs'

</details>
